// Lecture-Lab pairings: when a lecture is removed, its paired lab should also be removed
export const LECTURE_LAB_PAIRS: Record<string, string> = {
  "ASTR 10003": "ASTR 10001",  // Intro To Astronomy -> Astronomy Lab
  "ENSC 10003": "ENSC 10001",  // Intro To Environmental Science -> Environmental Science Lab
  "PHYS 10103": "PHYS 10101",  // Intro To Physics -> Physics Lab
}

// Course metadata
export const COURSES = [
  { id: "ANTH 10003", name: "Intro To Anthropology", credits: 3, category: "General Elective", sectionCount: 2, prereqMet: true },
  { id: "ASTR 10001", name: "Astronomy Lab", credits: 1, category: "State Min Core — Science Lab", sectionCount: 3, prereqMet: true, notes: "Lab — pairs with ASTR 10003" },
  { id: "ASTR 10003", name: "Intro To Astronomy", credits: 3, category: "State Min Core — Science", sectionCount: 2, prereqMet: true, notes: "Lecture — pair with ASTR 10001 lab" },
  { id: "BLAW 30303", name: "Business Entities", credits: 3, category: "Jr-Sr Business Elective", sectionCount: 2, prereqMet: true },
  { id: "COMM 13003", name: "Intro To Mass Media", credits: 3, category: "General Elective", sectionCount: 2, prereqMet: true },
  { id: "ECON 31303", name: "Intermediate Macroeconomics", credits: 3, category: "Economics Major", sectionCount: 1, prereqMet: true },
  { id: "ECON 31403", name: "International Trade", credits: 3, category: "Economics Elective", sectionCount: 1, prereqMet: true },
  { id: "ECON 33303", name: "Public Finance", credits: 3, category: "Economics Elective", sectionCount: 1, prereqMet: true },
  { id: "ECON 35303", name: "Economic Development", credits: 3, category: "Economics Elective", sectionCount: 1, prereqMet: true },
  { id: "ECON 43303", name: "Economics of Organizations", credits: 3, category: "Economics Major", sectionCount: 1, prereqMet: false, notes: "Prereq: ECON 30303 (in progress Fall 2026)" },
  { id: "ECON 44203", name: "Behavioral Economics", credits: 3, category: "Economics Elective", sectionCount: 1, prereqMet: true },
  { id: "ECON 44303", name: "Experimental Economics", credits: 3, category: "Economics Elective", sectionCount: 1, prereqMet: true },
  { id: "ECON 46303", name: "International Trade", credits: 3, category: "Economics Elective", sectionCount: 1, prereqMet: true },
  { id: "ECON 46403", name: "International Macro & Finance", credits: 3, category: "Economics Elective", sectionCount: 1, prereqMet: true },
  { id: "ECON 47403", name: "Introduction to Econometrics", credits: 4, category: "Economics Major", sectionCount: 2, prereqMet: true, notes: "4 credit hours" },
  { id: "ECON 47503", name: "Forecasting", credits: 4, category: "Economics Major", sectionCount: 2, prereqMet: true, notes: "4 credit hours" },
  { id: "ECON 47603", name: "Economic Analytics", credits: 4, category: "Economics Major", sectionCount: 1, prereqMet: true, notes: "4 credit hours. Alternative to ECON 47503." },
  { id: "ENSC 10001", name: "Environmental Science Lab", credits: 1, category: "State Min Core — Science Lab", sectionCount: 3, prereqMet: true, notes: "Lab — pairs with ENSC 10003" },
  { id: "ENSC 10003", name: "Intro To Environmental Science", credits: 3, category: "State Min Core — Science", sectionCount: 2, prereqMet: true, notes: "Lecture — pair with ENSC 10001 lab" },
  { id: "FINN 30003", name: "Personal Finance", credits: 3, category: "Finance Minor / Jr-Sr Elective", sectionCount: 5, prereqMet: true },
  { id: "FINN 30103", name: "Financial Analysis", credits: 3, category: "Finance Minor / Jr-Sr Elective", sectionCount: 3, prereqMet: true, notes: "Required for Finance minor. Unlocks FINN 30603, 36003, 31003." },
  { id: "FINN 30503", name: "Financial Markets & Institutions", credits: 3, category: "Finance Minor / Jr-Sr Elective", sectionCount: 6, prereqMet: true },
  { id: "FINN 30603", name: "Investments", credits: 3, category: "Finance Minor / Jr-Sr Elective", sectionCount: 5, prereqMet: false, notes: "Prereq not met: requires FINN 30103 (not taken)" },
  { id: "FINN 31003", name: "Financial Modeling", credits: 3, category: "Finance Minor / Jr-Sr Elective", sectionCount: 6, prereqMet: false, notes: "Prereq: FINN 30103 (not taken)" },
  { id: "FINN 31303", name: "Real Estate Finance", credits: 3, category: "Finance Minor / Jr-Sr Elective", sectionCount: 1, prereqMet: true },
  { id: "FINN 36003", name: "Corporate Finance", credits: 3, category: "Finance Minor / Jr-Sr Elective", sectionCount: 3, prereqMet: false, notes: "Prereq: FINN 30103 (not taken)" },
  { id: "FINN 36203", name: "International Finance", credits: 3, category: "Finance Minor / Jr-Sr Elective", sectionCount: 2, prereqMet: true },
  { id: "FINN 37003", name: "Bank Management", credits: 3, category: "Finance Minor / Jr-Sr Elective", sectionCount: 5, prereqMet: true },
  { id: "FINN 43203", name: "Derivatives", credits: 3, category: "Finance Minor / Jr-Sr Elective", sectionCount: 1, prereqMet: true },
  { id: "GEOS 10003", name: "World Regional Geography", credits: 3, category: "General Elective", sectionCount: 2, prereqMet: true },
  { id: "ISYS 41903", name: "Business Intelligence", credits: 3, category: "Jr-Sr Business Elective", sectionCount: 5, prereqMet: true },
  { id: "MGMT 42503", name: "Entrepreneurship", credits: 3, category: "Jr-Sr Business Elective", sectionCount: 8, prereqMet: true },
  { id: "MKTG 38303", name: "Consumer Behavior", credits: 3, category: "Jr-Sr Business Elective", sectionCount: 6, prereqMet: true },
  { id: "PHIL 32003", name: "Ethics", credits: 3, category: "General Elective", sectionCount: 2, prereqMet: true },
  { id: "PHYS 10101", name: "Physics Lab", credits: 1, category: "State Min Core — Science Lab", sectionCount: 3, prereqMet: true, notes: "Lab — pairs with PHYS 10103" },
  { id: "PHYS 10103", name: "Intro To Physics", credits: 3, category: "State Min Core — Science", sectionCount: 2, prereqMet: true, notes: "Lecture — pair with PHYS 10101 lab" },
  { id: "PSYC 21003", name: "Developmental Psychology", credits: 3, category: "General Elective", sectionCount: 2, prereqMet: true },
  { id: "SCMT 34403", name: "Transportation & Logistics", credits: 3, category: "Jr-Sr Business Elective", sectionCount: 7, prereqMet: true },
  { id: "SEVI 30103", name: "Strategic Management", credits: 3, category: "Business Core", sectionCount: 20, prereqMet: true, notes: "Capstone — requires C or better in all other business core courses" },
  { id: "SEVI 39303", name: "Business & Society", credits: 3, category: "Jr-Sr Business Elective", sectionCount: 7, prereqMet: true },
  { id: "SOCI 20003", name: "Social Problems", credits: 3, category: "General Elective", sectionCount: 2, prereqMet: true },
];

export type Course = typeof COURSES[number];

// Section data — 133 sections across 41 courses
export const SECTIONS = [
  { course: "ANTH 10003", section: "001", name: "Intro To Anthropology", days: "Tue/Thu", startTime: "9:30 AM", endTime: "10:45 AM", instructor: "TBA", location: "MAIN 212", cap: 60 },
  { course: "ANTH 10003", section: "002", name: "Intro To Anthropology", days: "Mon/Wed/Fri", startTime: "12:55 PM", endTime: "1:45 PM", instructor: "TBA", location: "MAIN 212", cap: 60 },
  { course: "ASTR 10001", section: "001", name: "Astronomy Lab", days: "Tue", startTime: "2:00 PM", endTime: "3:50 PM", instructor: "TBA", location: "PHYS 226", cap: 24 },
  { course: "ASTR 10001", section: "002", name: "Astronomy Lab", days: "Wed", startTime: "2:00 PM", endTime: "3:50 PM", instructor: "TBA", location: "PHYS 226", cap: 24 },
  { course: "ASTR 10001", section: "003", name: "Astronomy Lab", days: "Thu", startTime: "2:00 PM", endTime: "3:50 PM", instructor: "TBA", location: "PHYS 226", cap: 24 },
  { course: "ASTR 10003", section: "001", name: "Intro To Astronomy", days: "Mon/Wed/Fri", startTime: "10:45 AM", endTime: "11:35 AM", instructor: "TBA", location: "PHYS 133", cap: 120 },
  { course: "ASTR 10003", section: "002", name: "Intro To Astronomy", days: "Mon/Wed/Fri", startTime: "12:55 PM", endTime: "1:45 PM", instructor: "TBA", location: "PHYS 133", cap: 120 },
  { course: "BLAW 30303", section: "001", name: "Business Entities", days: "Mon/Wed/Fri", startTime: "12:55 PM", endTime: "1:45 PM", instructor: "Sarah Dobrzykowski", location: "WCOB 243", cap: 28 },
  { course: "BLAW 30303", section: "002", name: "Business Entities", days: "Mon/Wed/Fri", startTime: "2:00 PM", endTime: "2:50 PM", instructor: "Sarah Dobrzykowski", location: "WCOB 431", cap: 28 },
  { course: "COMM 13003", section: "001", name: "Intro To Mass Media", days: "Tue/Thu", startTime: "11:00 AM", endTime: "12:15 PM", instructor: "TBA", location: "KMPN 106", cap: 80 },
  { course: "COMM 13003", section: "002", name: "Intro To Mass Media", days: "Tue/Thu", startTime: "2:00 PM", endTime: "3:15 PM", instructor: "TBA", location: "KMPN 106", cap: 80 },
  { course: "ECON 31303", section: "001", name: "Intermediate Macroeconomics", days: "Tue/Thu", startTime: "9:30 AM", endTime: "10:45 AM", instructor: "Joao Pedro Rudge Leite", location: "SCEN 501", cap: 55 },
  { course: "ECON 31403", section: "001", name: "International Trade", days: "Mon/Wed/Fri", startTime: "10:45 AM", endTime: "11:35 AM", instructor: "TBA", location: "WCOB 339", cap: 40 },
  { course: "ECON 33303", section: "001", name: "Public Finance", days: "Tue/Thu", startTime: "12:30 PM", endTime: "1:45 PM", instructor: "Abel Embaye", location: "JBHT 234", cap: 34 },
  { course: "ECON 35303", section: "001", name: "Economic Development", days: "Tue/Thu", startTime: "12:30 PM", endTime: "1:45 PM", instructor: "TBA", location: "WCOB 339", cap: 35 },
  { course: "ECON 43303", section: "001", name: "Economics of Organizations", days: "Tue/Thu", startTime: "11:00 AM", endTime: "12:15 PM", instructor: "Ari Anisfeld", location: "WCOB 431", cap: 38 },
  { course: "ECON 44203", section: "001", name: "Behavioral Economics", days: "Tue/Thu", startTime: "2:00 PM", endTime: "3:15 PM", instructor: "Puja Bhattacharya", location: "WCOB 239", cap: 28 },
  { course: "ECON 44303", section: "001", name: "Experimental Economics", days: "Tue/Thu", startTime: "9:30 AM", endTime: "10:45 AM", instructor: "Sherry Li", location: "WCOB 239", cap: 28 },
  { course: "ECON 46303", section: "001", name: "International Trade", days: "Tue/Thu", startTime: "11:00 AM", endTime: "12:15 PM", instructor: "Difei Geng", location: "KIMP 306", cap: 60 },
  { course: "ECON 46403", section: "001", name: "International Macro & Finance", days: "Tue/Thu", startTime: "2:00 PM", endTime: "3:15 PM", instructor: "Andrew Yizhou Liu", location: "SCEN 501", cap: 50 },
  { course: "ECON 47403", section: "001", name: "Introduction to Econometrics", days: "Tue/Thu", startTime: "11:00 AM", endTime: "12:15 PM", instructor: "Md Amzad Hossain", location: "WCOB 433", cap: 20 },
  { course: "ECON 47403", section: "002", name: "Introduction to Econometrics", days: "Tue", startTime: "6:00 PM", endTime: "8:45 PM", instructor: "Shi Xu", location: "WCOB 437", cap: 20 },
  { course: "ECON 47503", section: "001", name: "Forecasting", days: "Tue/Thu", startTime: "3:30 PM", endTime: "4:45 PM", instructor: "Edder Fernando Martinez Lazo", location: "WCOB 339", cap: 20 },
  { course: "ECON 47503", section: "002", name: "Forecasting", days: "Tue/Thu", startTime: "9:30 AM", endTime: "10:45 AM", instructor: "Jingping Gu", location: "WCOB 243", cap: 25 },
  { course: "ECON 47603", section: "001", name: "Economic Analytics", days: "Tue/Thu", startTime: "2:00 PM", endTime: "3:15 PM", instructor: "TBA", location: "WCOB 437", cap: 20 },
  { course: "ENSC 10001", section: "001", name: "Environmental Science Lab", days: "Mon", startTime: "2:00 PM", endTime: "3:50 PM", instructor: "TBA", location: "SCEN 205", cap: 24 },
  { course: "ENSC 10001", section: "002", name: "Environmental Science Lab", days: "Wed", startTime: "2:00 PM", endTime: "3:50 PM", instructor: "TBA", location: "SCEN 205", cap: 24 },
  { course: "ENSC 10001", section: "003", name: "Environmental Science Lab", days: "Fri", startTime: "11:50 AM", endTime: "1:40 PM", instructor: "TBA", location: "SCEN 205", cap: 24 },
  { course: "ENSC 10003", section: "001", name: "Intro To Environmental Science", days: "Tue/Thu", startTime: "9:30 AM", endTime: "10:45 AM", instructor: "TBA", location: "SCEN 101", cap: 150 },
  { course: "ENSC 10003", section: "002", name: "Intro To Environmental Science", days: "Tue/Thu", startTime: "11:00 AM", endTime: "12:15 PM", instructor: "TBA", location: "SCEN 101", cap: 150 },
  { course: "FINN 30003", section: "001", name: "Personal Finance", days: "Mon/Wed/Fri", startTime: "8:35 AM", endTime: "9:25 AM", instructor: "Mara Lynch", location: "KIMP 112", cap: 48 },
  { course: "FINN 30003", section: "002", name: "Personal Finance", days: "Mon/Wed/Fri", startTime: "9:40 AM", endTime: "10:30 AM", instructor: "Mara Lynch", location: "WCOB 241", cap: 72 },
  { course: "FINN 30003", section: "003", name: "Personal Finance", days: "Tue/Thu", startTime: "5:00 PM", endTime: "6:15 PM", instructor: "Gil Woods", location: "WCOB 257", cap: 84 },
  { course: "FINN 30003", section: "004", name: "Personal Finance", days: "Tue/Thu", startTime: "3:30 PM", endTime: "4:45 PM", instructor: "Mara Lynch", location: "WCOB 257", cap: 84 },
  { course: "FINN 30003", section: "005", name: "Personal Finance", days: "Tue/Thu", startTime: "12:30 PM", endTime: "1:45 PM", instructor: "Stuart G Baber", location: "WCOB 235", cap: 72 },
  { course: "FINN 30103", section: "001", name: "Financial Analysis", days: "Tue/Thu", startTime: "11:00 AM", endTime: "12:15 PM", instructor: "Cash Acrey", location: "RCED 120", cap: 270 },
  { course: "FINN 30103", section: "002", name: "Financial Analysis", days: "Tue/Thu", startTime: "8:00 AM", endTime: "9:15 AM", instructor: "Eric Dubowsky", location: "WCOB 116", cap: 65 },
  { course: "FINN 30103", section: "003", name: "Financial Analysis", days: "Tue/Thu", startTime: "12:30 PM", endTime: "1:45 PM", instructor: "Eric Dubowsky", location: "WJWH 403", cap: 65 },
  { course: "FINN 30503", section: "001", name: "Financial Markets & Institutions", days: "Tue/Thu", startTime: "8:00 AM", endTime: "9:15 AM", instructor: "Kuan Liu", location: "SCEN 408", cap: 75 },
  { course: "FINN 30503", section: "002", name: "Financial Markets & Institutions", days: "Tue", startTime: "6:00 PM", endTime: "8:45 PM", instructor: "Kuan Liu", location: "SCEN 407", cap: 80 },
  { course: "FINN 30503", section: "003", name: "Financial Markets & Institutions", days: "Wed", startTime: "6:00 PM", endTime: "8:45 PM", instructor: "Kuan Liu", location: "SCEN 407", cap: 75 },
  { course: "FINN 30503", section: "004", name: "Financial Markets & Institutions", days: "Mon/Wed/Fri", startTime: "10:45 AM", endTime: "11:35 AM", instructor: "John Hackney", location: "SCEN 403", cap: 75 },
  { course: "FINN 30503", section: "005", name: "Financial Markets & Institutions", days: "Mon/Wed/Fri", startTime: "12:55 PM", endTime: "1:45 PM", instructor: "John Hackney", location: "SCEN 408", cap: 75 },
  { course: "FINN 30503", section: "006", name: "Financial Markets & Institutions", days: "Mon/Wed/Fri", startTime: "2:00 PM", endTime: "2:50 PM", instructor: "John Hackney", location: "RCED 117", cap: 75 },
  { course: "FINN 30603", section: "001", name: "Investments", days: "Mon", startTime: "6:00 PM", endTime: "8:45 PM", instructor: "Xi Li", location: "WJWH 403", cap: 60 },
  { course: "FINN 30603", section: "003", name: "Investments", days: "Tue/Thu", startTime: "9:30 AM", endTime: "10:45 AM", instructor: "Eric Dubowsky", location: "WJWH 331", cap: 60 },
  { course: "FINN 30603", section: "004", name: "Investments", days: "Tue/Thu", startTime: "12:30 PM", endTime: "1:45 PM", instructor: "Sergio F Santamaria", location: "WJWH 331", cap: 60 },
  { course: "FINN 30603", section: "005", name: "Investments", days: "Tue/Thu", startTime: "3:30 PM", endTime: "4:45 PM", instructor: "Ken McGovern", location: "WJWH 331", cap: 60 },
  { course: "FINN 30603", section: "006", name: "Investments", days: "Tue/Thu", startTime: "11:00 AM", endTime: "12:15 PM", instructor: "Eric Dubowsky", location: "WJWH 331", cap: 60 },
  { course: "FINN 31003", section: "001", name: "Financial Modeling", days: "Mon/Wed/Fri", startTime: "8:35 AM", endTime: "9:25 AM", instructor: "Lifa Huang", location: "WJWH 331", cap: 60 },
  { course: "FINN 31003", section: "002", name: "Financial Modeling", days: "Mon/Wed/Fri", startTime: "9:40 AM", endTime: "10:30 AM", instructor: "Lifa Huang", location: "WJWH 331", cap: 60 },
  { course: "FINN 31003", section: "003", name: "Financial Modeling", days: "Mon/Wed/Fri", startTime: "12:55 PM", endTime: "1:45 PM", instructor: "Lifa Huang", location: "WJWH 331", cap: 60 },
  { course: "FINN 31003", section: "004", name: "Financial Modeling", days: "Mon/Wed/Fri", startTime: "2:00 PM", endTime: "2:50 PM", instructor: "Lifa Huang", location: "WJWH 331", cap: 60 },
  { course: "FINN 31003", section: "005", name: "Financial Modeling", days: "Mon/Wed/Fri", startTime: "10:45 AM", endTime: "11:35 AM", instructor: "Mark Chisenhall", location: "WJWH 331", cap: 60 },
  { course: "FINN 31003", section: "006", name: "Financial Modeling", days: "Mon/Wed/Fri", startTime: "11:50 AM", endTime: "12:40 PM", instructor: "Mark Chisenhall", location: "WJWH 331", cap: 60 },
  { course: "FINN 31303", section: "001", name: "Real Estate Finance", days: "Tue/Thu", startTime: "2:00 PM", endTime: "3:15 PM", instructor: "Timothy J Yeager", location: "KIMP 306", cap: 60 },
  { course: "FINN 36003", section: "001", name: "Corporate Finance", days: "Tue/Thu", startTime: "11:00 AM", endTime: "12:15 PM", instructor: "Yu Wang", location: "WCOB 202", cap: 68 },
  { course: "FINN 36003", section: "002", name: "Corporate Finance", days: "Tue/Thu", startTime: "12:30 PM", endTime: "1:45 PM", instructor: "Yu Wang", location: "SCEN 501", cap: 55 },
  { course: "FINN 36003", section: "003", name: "Corporate Finance", days: "Tue/Thu", startTime: "3:30 PM", endTime: "4:45 PM", instructor: "Yu Wang", location: "WCOB 241", cap: 68 },
  { course: "FINN 36203", section: "001", name: "International Finance", days: "Tue/Thu", startTime: "9:30 AM", endTime: "10:45 AM", instructor: "Nelson G Driver", location: "WCOB 234", cap: 65 },
  { course: "FINN 36203", section: "002", name: "International Finance", days: "Tue/Thu", startTime: "11:00 AM", endTime: "12:15 PM", instructor: "Nelson G Driver", location: "WCOB 234", cap: 65 },
  { course: "FINN 37003", section: "001", name: "Bank Management", days: "Tue/Thu", startTime: "8:00 AM", endTime: "9:15 AM", instructor: "Dobrina Georgieva Jandik", location: "SCEN 407", cap: 80 },
  { course: "FINN 37003", section: "002", name: "Bank Management", days: "Tue/Thu", startTime: "9:30 AM", endTime: "10:45 AM", instructor: "Dobrina Georgieva Jandik", location: "RCED 117", cap: 80 },
  { course: "FINN 37003", section: "003", name: "Bank Management", days: "Tue/Thu", startTime: "3:30 PM", endTime: "4:45 PM", instructor: "Dier Gao", location: "WJWH 427", cap: 70 },
  { course: "FINN 37003", section: "004", name: "Bank Management", days: "Tue/Thu", startTime: "11:00 AM", endTime: "12:15 PM", instructor: "Dobrina Georgieva Jandik", location: "WJWH 427", cap: 71 },
  { course: "FINN 37003", section: "005", name: "Bank Management", days: "Tue/Thu", startTime: "2:00 PM", endTime: "3:15 PM", instructor: "Yan Li", location: "WJWH 124", cap: 80 },
  { course: "FINN 43203", section: "001", name: "Derivatives", days: "Wed", startTime: "6:00 PM", endTime: "8:45 PM", instructor: "Alejandro Pacheco", location: "WJWH 331", cap: 30 },
  { course: "GEOS 10003", section: "001", name: "World Regional Geography", days: "Mon/Wed/Fri", startTime: "11:50 AM", endTime: "12:40 PM", instructor: "TBA", location: "OZRK 017", cap: 80 },
  { course: "GEOS 10003", section: "002", name: "World Regional Geography", days: "Tue/Thu", startTime: "9:30 AM", endTime: "10:45 AM", instructor: "TBA", location: "OZRK 017", cap: 80 },
  { course: "ISYS 41903", section: "001", name: "Business Intelligence", days: "Tue/Thu", startTime: "2:00 PM", endTime: "3:15 PM", instructor: "Jana Gastineau", location: "RCED 203", cap: 34 },
  { course: "ISYS 41903", section: "004", name: "Business Intelligence", days: "Mon/Wed/Fri", startTime: "9:40 AM", endTime: "10:30 AM", instructor: "Carole Shook", location: "JBHT 220", cap: 34 },
  { course: "ISYS 41903", section: "005", name: "Business Intelligence", days: "Mon/Wed/Fri", startTime: "10:45 AM", endTime: "11:35 AM", instructor: "Carole Shook", location: "JBHT 220", cap: 34 },
  { course: "ISYS 41903", section: "006", name: "Business Intelligence", days: "Tue/Thu", startTime: "11:00 AM", endTime: "12:15 PM", instructor: "Jana Gastineau", location: "WCOB 112", cap: 34 },
  { course: "ISYS 41903", section: "007", name: "Business Intelligence", days: "Mon/Wed/Fri", startTime: "11:50 AM", endTime: "12:40 PM", instructor: "Carole Shook", location: "JBHT 220", cap: 35 },
  { course: "MGMT 42503", section: "001", name: "Entrepreneurship", days: "Tue/Thu", startTime: "2:00 PM", endTime: "3:15 PM", instructor: "Robert Allen Foster", location: "KIMP 305", cap: 43 },
  { course: "MGMT 42503", section: "002", name: "Entrepreneurship", days: "Mon/Wed/Fri", startTime: "10:45 AM", endTime: "11:35 AM", instructor: "Mandi Cooper", location: "KIMP 310", cap: 43 },
  { course: "MGMT 42503", section: "003", name: "Entrepreneurship", days: "Fri", startTime: "2:00 PM", endTime: "4:50 PM", instructor: "Rich Lawrence", location: "JBHT 149", cap: 43 },
  { course: "MGMT 42503", section: "004", name: "Entrepreneurship", days: "Mon/Wed/Fri", startTime: "11:50 AM", endTime: "12:40 PM", instructor: "Mandi Cooper", location: "WJWH 103", cap: 40 },
  { course: "MGMT 42503", section: "005", name: "Entrepreneurship", days: "Mon/Wed/Fri", startTime: "8:35 AM", endTime: "9:25 AM", instructor: "Mandi Cooper", location: "KIMP 305", cap: 43 },
  { course: "MGMT 42503", section: "006", name: "Entrepreneurship", days: "Tue/Thu", startTime: "11:00 AM", endTime: "12:15 PM", instructor: "Robert Allen Foster", location: "WJWH 103", cap: 43 },
  { course: "MGMT 42503", section: "007", name: "Entrepreneurship", days: "Tue/Thu", startTime: "3:30 PM", endTime: "4:45 PM", instructor: "Robert Allen Foster", location: "WJWH 303", cap: 40 },
  { course: "MGMT 42503", section: "601", name: "Entrepreneurship", days: "Wed", startTime: "9:15 AM", endTime: "12:00 PM", instructor: "Fabio Pisi Vitagliano", location: "", cap: 16 },
  { course: "MKTG 38303", section: "003", name: "Consumer Behavior", days: "Mon", startTime: "6:00 PM", endTime: "8:45 PM", instructor: "CAROLINA RODRIGUEZ", location: "KIMP 209", cap: 46 },
  { course: "MKTG 38303", section: "004", name: "Consumer Behavior", days: "Mon/Wed/Fri", startTime: "8:35 AM", endTime: "9:25 AM", instructor: "SHANE JENNINGS", location: "WJWH 303", cap: 40 },
  { course: "MKTG 38303", section: "005", name: "Consumer Behavior", days: "Tue", startTime: "5:00 PM", endTime: "7:45 PM", instructor: "Mychael Stewart", location: "WJWH 302", cap: 42 },
  { course: "MKTG 38303", section: "006", name: "Consumer Behavior", days: "Tue/Thu", startTime: "12:30 PM", endTime: "1:45 PM", instructor: "Taylor Blackwell", location: "WJWH 302", cap: 42 },
  { course: "MKTG 38303", section: "007", name: "Consumer Behavior", days: "Tue/Thu", startTime: "2:00 PM", endTime: "3:15 PM", instructor: "CAROLINA RODRIGUEZ", location: "WJWH 303", cap: 42 },
  { course: "MKTG 38303", section: "010", name: "Consumer Behavior", days: "Tue", startTime: "5:00 PM", endTime: "7:45 PM", instructor: "CAROLINA RODRIGUEZ", location: "JBHT 147", cap: 46 },
  { course: "PHIL 32003", section: "001", name: "Ethics", days: "Mon/Wed/Fri", startTime: "9:40 AM", endTime: "10:30 AM", instructor: "TBA", location: "MAIN 320", cap: 35 },
  { course: "PHIL 32003", section: "002", name: "Ethics", days: "Tue/Thu", startTime: "12:30 PM", endTime: "1:45 PM", instructor: "TBA", location: "MAIN 320", cap: 35 },
  { course: "PHYS 10101", section: "001", name: "Physics Lab", days: "Tue", startTime: "3:30 PM", endTime: "5:20 PM", instructor: "TBA", location: "PHYS 117", cap: 24 },
  { course: "PHYS 10101", section: "002", name: "Physics Lab", days: "Thu", startTime: "3:30 PM", endTime: "5:20 PM", instructor: "TBA", location: "PHYS 117", cap: 24 },
  { course: "PHYS 10101", section: "003", name: "Physics Lab", days: "Wed", startTime: "3:30 PM", endTime: "5:20 PM", instructor: "TBA", location: "PHYS 117", cap: 24 },
  { course: "PHYS 10103", section: "001", name: "Intro To Physics", days: "Mon/Wed/Fri", startTime: "9:40 AM", endTime: "10:30 AM", instructor: "TBA", location: "PHYS 133", cap: 100 },
  { course: "PHYS 10103", section: "002", name: "Intro To Physics", days: "Mon/Wed/Fri", startTime: "11:50 AM", endTime: "12:40 PM", instructor: "TBA", location: "PHYS 133", cap: 100 },
  { course: "PSYC 21003", section: "001", name: "Developmental Psychology", days: "Mon/Wed/Fri", startTime: "10:45 AM", endTime: "11:35 AM", instructor: "TBA", location: "SCEN 408", cap: 60 },
  { course: "PSYC 21003", section: "002", name: "Developmental Psychology", days: "Tue/Thu", startTime: "12:30 PM", endTime: "1:45 PM", instructor: "TBA", location: "SCEN 408", cap: 60 },
  { course: "SCMT 34403", section: "001", name: "Transportation & Logistics", days: "Tue/Thu", startTime: "9:30 AM", endTime: "10:45 AM", instructor: "Don Bechtel", location: "HLTH 1117A", cap: 46 },
  { course: "SCMT 34403", section: "002", name: "Transportation & Logistics", days: "Tue/Thu", startTime: "2:00 PM", endTime: "3:15 PM", instructor: "Don Bechtel", location: "WCOB 203", cap: 46 },
  { course: "SCMT 34403", section: "003", name: "Transportation & Logistics", days: "Tue/Thu", startTime: "12:30 PM", endTime: "1:45 PM", instructor: "Donnie F Williams Jr.", location: "WJWH 103", cap: 46 },
  { course: "SCMT 34403", section: "004", name: "Transportation & Logistics", days: "Tue/Thu", startTime: "11:00 AM", endTime: "12:15 PM", instructor: "Donnie F Williams Jr.", location: "GEAR 108", cap: 46 },
  { course: "SCMT 34403", section: "007", name: "Transportation & Logistics", days: "Tue/Thu", startTime: "2:00 PM", endTime: "3:15 PM", instructor: "Judith Jacquelyn Thorne", location: "WJWH 103", cap: 46 },
  { course: "SCMT 34403", section: "008", name: "Transportation & Logistics", days: "Tue/Thu", startTime: "3:30 PM", endTime: "4:45 PM", instructor: "Donnie F Williams Jr.", location: "WCOB 239", cap: 28 },
  { course: "SCMT 34403", section: "009", name: "Transportation & Logistics", days: "Mon", startTime: "6:00 PM", endTime: "8:50 PM", instructor: "Lisha Yates", location: "RCED 103", cap: 36 },
  { course: "SEVI 30103", section: "001", name: "Strategic Management", days: "Mon/Wed/Fri", startTime: "9:40 AM", endTime: "10:30 AM", instructor: "Christian Baldwin", location: "JBHT 148", cap: 48 },
  { course: "SEVI 30103", section: "002", name: "Strategic Management", days: "Mon/Wed/Fri", startTime: "10:45 AM", endTime: "11:35 AM", instructor: "Amrit Panda", location: "JBHT 148", cap: 48 },
  { course: "SEVI 30103", section: "003", name: "Strategic Management", days: "Mon/Wed", startTime: "4:35 PM", endTime: "5:50 PM", instructor: "Joshua McCullough", location: "WJWH 103", cap: 44 },
  { course: "SEVI 30103", section: "004", name: "Strategic Management", days: "Mon/Wed/Fri", startTime: "12:55 PM", endTime: "1:45 PM", instructor: "Hannah Davis", location: "JBHT 147", cap: 50 },
  { course: "SEVI 30103", section: "005", name: "Strategic Management", days: "Mon/Wed/Fri", startTime: "2:00 PM", endTime: "2:50 PM", instructor: "Hannah Davis", location: "JBHT 147", cap: 48 },
  { course: "SEVI 30103", section: "006", name: "Strategic Management", days: "Mon/Wed/Fri", startTime: "3:05 PM", endTime: "3:55 PM", instructor: "Hannah Davis", location: "JBHT 147", cap: 50 },
  { course: "SEVI 30103", section: "007", name: "Strategic Management", days: "Tue/Thu", startTime: "8:00 AM", endTime: "9:15 AM", instructor: "William P Welsh", location: "JBHT 148", cap: 49 },
  { course: "SEVI 30103", section: "008", name: "Strategic Management", days: "Tue/Thu", startTime: "9:30 AM", endTime: "10:45 AM", instructor: "Johnny Smith", location: "JBHT 149", cap: 46 },
  { course: "SEVI 30103", section: "009", name: "Strategic Management", days: "Tue/Thu", startTime: "11:00 AM", endTime: "12:15 PM", instructor: "William P Welsh", location: "JBHT 146", cap: 48 },
  { course: "SEVI 30103", section: "010", name: "Strategic Management", days: "Tue/Thu", startTime: "12:30 PM", endTime: "1:45 PM", instructor: "Shaughan Sparks Cummings", location: "JBHT 148", cap: 48 },
  { course: "SEVI 30103", section: "011", name: "Strategic Management", days: "Tue/Thu", startTime: "2:00 PM", endTime: "3:15 PM", instructor: "William P Welsh", location: "JBHT 147", cap: 48 },
  { course: "SEVI 30103", section: "012", name: "Strategic Management", days: "Tue/Thu", startTime: "3:30 PM", endTime: "4:45 PM", instructor: "Jesse Core", location: "WCOB 431", cap: 40 },
  { course: "SEVI 30103", section: "013", name: "Strategic Management", days: "Tue/Thu", startTime: "5:00 PM", endTime: "6:15 PM", instructor: "Jesse Core", location: "JBHT 148", cap: 48 },
  { course: "SEVI 30103", section: "014", name: "Strategic Management", days: "Mon/Wed", startTime: "5:00 PM", endTime: "6:15 PM", instructor: "David Paul", location: "JBHT 146", cap: 48 },
  { course: "SEVI 30103", section: "015", name: "Strategic Management", days: "Mon/Wed", startTime: "6:30 PM", endTime: "7:45 PM", instructor: "David Paul", location: "WCOB 431", cap: 42 },
  { course: "SEVI 30103", section: "016", name: "Strategic Management", days: "Tue/Thu", startTime: "8:00 AM", endTime: "9:15 AM", instructor: "Shaughan Sparks Cummings", location: "JBHT 146", cap: 48 },
  { course: "SEVI 30103", section: "017", name: "Strategic Management", days: "Tue/Thu", startTime: "9:30 AM", endTime: "10:45 AM", instructor: "Ryan Cooper", location: "JBHT 147", cap: 50 },
  { course: "SEVI 30103", section: "018", name: "Strategic Management", days: "Tue/Thu", startTime: "11:00 AM", endTime: "12:15 PM", instructor: "Ryan Cooper", location: "JBHT 239", cap: 42 },
  { course: "SEVI 30103", section: "019", name: "Strategic Management", days: "Tue/Thu", startTime: "12:30 PM", endTime: "1:45 PM", instructor: "Joel Andrus", location: "JBHT 147", cap: 50 },
  { course: "SEVI 30103", section: "020", name: "Strategic Management", days: "Tue/Thu", startTime: "2:00 PM", endTime: "3:15 PM", instructor: "Joel Andrus", location: "JBHT 148", cap: 48 },
  { course: "SEVI 39303", section: "001", name: "Business & Society", days: "Tue/Thu", startTime: "8:00 AM", endTime: "9:15 AM", instructor: "Nur Ahmed", location: "WJWH 114", cap: 40 },
  { course: "SEVI 39303", section: "002", name: "Business & Society", days: "Tue/Thu", startTime: "3:30 PM", endTime: "4:45 PM", instructor: "Jake B Grandy", location: "SCEN 610", cap: 38 },
  { course: "SEVI 39303", section: "003", name: "Business & Society", days: "Tue/Thu", startTime: "11:00 AM", endTime: "12:15 PM", instructor: "Jake B Grandy", location: "WJWH 303", cap: 40 },
  { course: "SEVI 39303", section: "004", name: "Business & Society", days: "Tue/Thu", startTime: "12:30 PM", endTime: "1:45 PM", instructor: "Nur Ahmed", location: "PEAH 307", cap: 38 },
  { course: "SEVI 39303", section: "005", name: "Business & Society", days: "Tue/Thu", startTime: "2:00 PM", endTime: "3:15 PM", instructor: "Nur Ahmed", location: "HOEC 5", cap: 38 },
  { course: "SEVI 39303", section: "008", name: "Business & Society", days: "Tue", startTime: "6:00 PM", endTime: "8:45 PM", instructor: "Michael E Cummings", location: "WJWH 114", cap: 40 },
  { course: "SEVI 39303", section: "601", name: "Business & Society", days: "Mon", startTime: "9:30 AM", endTime: "12:15 PM", instructor: "Vincenzo Mazzotta", location: "", cap: 16 },
  { course: "SOCI 20003", section: "001", name: "Social Problems", days: "Tue/Thu", startTime: "11:00 AM", endTime: "12:15 PM", instructor: "TBA", location: "MAIN 425", cap: 45 },
  { course: "SOCI 20003", section: "002", name: "Social Problems", days: "Tue/Thu", startTime: "2:00 PM", endTime: "3:15 PM", instructor: "TBA", location: "MAIN 425", cap: 45 },
];

export type Section = typeof SECTIONS[number];

// Optimal schedule (result of Optimize with 'Prefer mornings' + 'Work Thu 1-5 PM')
export const OPTIMAL_SECTIONS = [
  { course: "SEVI 30103", section: "001" },
  { course: "ASTR 10003", section: "001" },
  { course: "FINN 30103", section: "002" },
  { course: "ECON 31303", section: "001" },
  { course: "ECON 47403", section: "001" },
  { course: "ASTR 10001", section: "001" },
];

// Courses selected by the student (for demo default state)
export const SELECTED_COURSES = [
  "SEVI 30103", "ECON 31303", "ECON 47403", "FINN 30103",
  "ASTR 10003", "ASTR 10001", "ENSC 10003", "ENSC 10001", "PHYS 10103", "PHYS 10101",
];

// Semester availability data for graduation path check
export const COURSE_AVAILABILITY = [
  // Economics Major — Required
  { course: "ECON 43303", name: "Economics of Organizations", offered: "Fall", required: true, prereq: "ECON 30303", prereqMet: false, prereqNote: "In progress Fall 2026" },
  { course: "ECON 47503", name: "Forecasting", offered: "Fall", required: true, prereq: "ECON 47403 or equivalent", prereqMet: false, prereqNote: "Planned Spring 2027" },
  { course: "ECON 47603", name: "Economic Analytics", offered: "Fall", required: false, prereq: "ECON 47403 or ISYS 41903", prereqMet: false, prereqNote: "Alternative to 47503. Planned Spring 2027" },
  
  // Economics Electives
  { course: "ECON 46303", name: "International Trade", offered: "Fall and Spring", required: false, prereqMet: true },
  { course: "ECON 46403", name: "International Macro & Finance", offered: "Fall and Spring", required: false, prereqMet: true },
  { course: "ECON 38403", name: "Economics of the Developing World", offered: "Fall and Spring", required: false, prereqMet: true },
  { course: "ECON 44203", name: "Behavioral Economics", offered: "Fall", required: false, prereq: "ECON 30303", prereqMet: false, prereqNote: "In progress Fall 2026" },
  { course: "ECON 44303", name: "Experimental Economics", offered: "Spring", required: false, prereqMet: true },
  { course: "ECON 31403", name: "Poverty & Inequality", offered: "Fall", required: false, prereqMet: true },
  { course: "ECON 38503", name: "Emerging Markets", offered: "Fall", required: false, prereqMet: true },
  { course: "ECON 33303", name: "Public Economics", offered: "Irregular", required: false, prereqMet: true },
  { course: "ECON 35303", name: "Labor Economics", offered: "Irregular", required: false, prereqMet: true },
  { course: "ECON 36303", name: "Economics of Advertising", offered: "Irregular", required: false, prereqMet: true },
  
  // Finance Minor — Group A (need 2)
  { course: "FINN 30503", name: "Financial Markets & Institutions", offered: "Fall, Spring, Summer", required: true, prereqMet: true },
  { course: "FINN 31003", name: "Financial Modeling", offered: "Fall, Spring, Summer", required: true, prereq: "FINN 20403", prereqMet: true },
  { course: "FINN 37003", name: "International Finance", offered: "Fall, Spring, Summer", required: true, prereqMet: true },

  // Finance Minor — Group B (need 2)
  { course: "FINN 30603", name: "Investments", offered: "Fall, Spring, Summer", required: true, prereq: "FINN 30103", prereqMet: false, prereqNote: "Planned Spring 2027" },
  { course: "FINN 31303", name: "Commercial Banking", offered: "Fall and Spring", required: false, prereq: "FINN 20403", prereqMet: true },
  { course: "FINN 36003", name: "Corporate Finance", offered: "Fall, Spring, Summer", required: false, prereq: "FINN 30103", prereqMet: false, prereqNote: "Planned Spring 2027" },
  { course: "FINN 41303", name: "Advanced Investments", offered: "Fall and Spring", required: false, prereq: "FINN 30603", prereqMet: false, prereqNote: "Must take FINN 30603 first" },
  { course: "FINN 43103", name: "Advanced Commercial Banking", offered: "Spring", required: false, prereq: "FINN 31303", prereqMet: false },
  { course: "FINN 43203", name: "Derivatives", offered: "Fall", required: false, prereq: "FINN 30603", prereqMet: false, prereqNote: "1-credit add-on" },
];

// Suggested semester plans for graduation path
export const SUGGESTED_FALL_2027 = [
  { course: "ECON 43303", name: "Economics of Organizations", hrs: 3, reason: "Fall only — required for major. No alternative." },
  { course: "ECON 47503", name: "Forecasting", hrs: 3, reason: "Fall only — required for major. (Or take ECON 47603 instead — also Fall only.)" },
  { course: "ECON 46303", name: "International Trade", hrs: 3, reason: "Econ elective — offered both semesters, but taking it here balances the load." },
  { course: "FINN 30603", name: "Investments", hrs: 3, reason: "Finance minor Group B. Prereq FINN 30103 will be met. Also counts as Jr/Sr business elective." },
];

export const SUGGESTED_SPRING_2028 = [
  { course: "FINN 37003", name: "International Finance", hrs: 3, reason: "Finance minor Group A. Offered both semesters — Spring works." },
  { course: "FINN 30503", name: "Financial Markets & Institutions", hrs: 3, reason: "Finance minor Group A. Offered both semesters. Also counts as Jr/Sr business elective." },
  { course: "FINN 36003", name: "Corporate Finance", hrs: 3, reason: "Finance minor Group B. Prereq FINN 30103 met. Also Jr/Sr elective." },
  { course: "GEN ELEC", name: "General Elective", hrs: 3, reason: "Any 3-hr course. Light final semester — focus on senior capstone work." },
];

// ECON elective options table
export const ECON_ELECTIVE_OPTIONS = [
  { course: "ECON 46303", name: "International Trade", offered: "Fall and Spring", prereqMet: true, notes: "Recommended — flexible timing" },
  { course: "ECON 46403", name: "International Macro & Finance", offered: "Fall and Spring", prereqMet: true, notes: "Good alternative" },
  { course: "ECON 38403", name: "Econ of Developing World", offered: "Fall and Spring", prereqMet: true, notes: "" },
  { course: "ECON 44203", name: "Behavioral Economics", offered: "Fall only", prereqMet: true, notes: "Would add to Fall 2027 load" },
  { course: "ECON 44303", name: "Experimental Economics", offered: "Spring only", prereqMet: true, notes: "Spring option if preferred" },
  { course: "ECON 31403", name: "Poverty & Inequality", offered: "Fall only", prereqMet: true, notes: "Would add to Fall 2027 load" },
  { course: "ECON 33303", name: "Public Finance", offered: "Irregular", prereqMet: true, notes: "May not be offered — risky to plan around" },
  { course: "ECON 35303", name: "Labor Economics", offered: "Irregular", prereqMet: true, notes: "May not be offered — risky to plan around" },
];
